import { createRNG } from './eu4-utils'

// ─── Culture groups with historically-flavored fictional names ────────────────

export const CULTURE_GROUPS: Record<
  string,
  { names: string[]; adjectives: string[] }
> = {
  germanic: {
    names: [
      'Franconia',
      'Alemania',
      'Saxony',
      'Bavaria',
      'Thuringia',
      'Brunswick',
      'Friesland',
      'Brandenburg',
      'Pomerania',
      'Holstein',
      'Westphalia',
      'Swabia',
      'Hessia',
      'Lusatia',
      'Anglia',
      'Gotland',
      'Nordmark',
      'Rhineland',
      'Austrasia',
      'Vandalia',
    ],
    adjectives: [
      'Franconian',
      'Aleman',
      'Saxon',
      'Bavarian',
      'Thuringian',
      'Brunswicker',
      'Frisian',
      'Brandenburger',
      'Pomeranian',
      'Holsteiner',
      'Westphalian',
      'Swabian',
      'Hessian',
      'Lusatian',
      'Anglian',
      'Gothic',
      'Nordic',
      'Rhenish',
      'Austrasian',
      'Vandalic',
    ],
  },
  latin: {
    names: [
      'Gallia',
      'Hispania',
      'Lusitania',
      'Italia',
      'Sicilia',
      'Sardinia',
      'Corsica',
      'Aquitania',
      'Burgundia',
      'Provincia',
      'Lombardia',
      'Tuscania',
      'Venetia',
      'Neapolis',
      'Romagna',
      'Picenum',
      'Apulia',
      'Caledonia',
      'Wallachia',
      'Dacia',
    ],
    adjectives: [
      'Gallic',
      'Hispanic',
      'Lusitanian',
      'Italian',
      'Sicilian',
      'Sardinian',
      'Corsican',
      'Aquitanian',
      'Burgundian',
      'Provencal',
      'Lombard',
      'Tuscan',
      'Venetian',
      'Neapolitan',
      'Romagnan',
      'Picene',
      'Apulian',
      'Caledonian',
      'Wallachian',
      'Dacian',
    ],
  },
  slavic: {
    names: [
      'Polonia',
      'Ruthenia',
      'Muscovy',
      'Novgorod',
      'Bohemia',
      'Moravia',
      'Serbia',
      'Croatia',
      'Bulgaria',
      'Pomerania',
      'Silesia',
      'Galicia',
      'Volhynia',
      'Smolensk',
      'Chernigov',
      'Krakow',
      'Mazovia',
      'Slovakia',
      'Carniola',
      'Bosnia',
    ],
    adjectives: [
      'Polish',
      'Ruthenian',
      'Muscovite',
      'Novgorodian',
      'Bohemian',
      'Moravian',
      'Serbian',
      'Croatian',
      'Bulgarian',
      'Pomeranian',
      'Silesian',
      'Galician',
      'Volhynian',
      'Smolenskan',
      'Chernigovan',
      'Krakovian',
      'Mazovian',
      'Slovak',
      'Carniolan',
      'Bosnian',
    ],
  },
  turkic: {
    names: [
      'Ottoman',
      'Rum',
      'Karaman',
      'Aq Qoyunlu',
      'Qara Qoyunlu',
      'Kazan',
      'Crimea',
      'Nogai',
      'Khiva',
      'Bukhara',
      'Chagatai',
      'Timurids',
      'Great Horde',
      'Astrakhan',
      'Sibir',
      'Kazakh',
      'Uzbek',
      'Oirat',
      'Mongolia',
      'Yarkand',
    ],
    adjectives: [
      'Ottoman',
      'Rumi',
      'Karamanid',
      'Aq Qoyunlu',
      'Qara Qoyunlu',
      'Kazani',
      'Crimean',
      'Nogai',
      'Khivan',
      'Bukharan',
      'Chagatai',
      'Timurid',
      'Horde',
      'Astrakhani',
      'Sibirian',
      'Kazakh',
      'Uzbek',
      'Oirat',
      'Mongol',
      'Yarkandi',
    ],
  },
  indic: {
    names: [
      'Hindustan',
      'Bengal',
      'Gujarat',
      'Malwa',
      'Mewar',
      'Vijayanagar',
      'Bahmanis',
      'Orissa',
      'Delhi',
      'Multan',
      'Sindh',
      'Kashmir',
      'Nepal',
      'Assam',
      'Jaunpur',
      'Gondwana',
      'Maratha',
      'Mysore',
      'Travancore',
      'Punjab',
    ],
    adjectives: [
      'Hindustani',
      'Bengali',
      'Gujarati',
      'Malwi',
      'Mewari',
      'Vijayanagari',
      'Bahmani',
      'Oriya',
      'Delhian',
      'Multani',
      'Sindhi',
      'Kashmiri',
      'Nepali',
      'Assamese',
      'Jaunpuri',
      'Gondi',
      'Marathi',
      'Mysorean',
      'Travancori',
      'Punjabi',
    ],
  },
  east_asian: {
    names: [
      'Great Ming',
      'Joseon',
      'Yamato',
      'Dai Viet',
      'Lan Xang',
      'Ayutthaya',
      'Khmer',
      'Tibet',
      'Manchu',
      'Great Jin',
      'Tangut',
      'Uesugi',
      'Shimazu',
      'Oda',
      'Ryukyu',
      'Malacca',
      'Majapahit',
      'Pegu',
      'Ava',
      'Champa',
    ],
    adjectives: [
      'Ming',
      'Joseon',
      'Japanese',
      'Vietnamese',
      'Lao',
      'Thai',
      'Khmer',
      'Tibetan',
      'Manchu',
      'Jurchen',
      'Tangut',
      'Uesugi',
      'Shimazu',
      'Oda',
      'Ryukyuan',
      'Malaccan',
      'Javanese',
      'Pegu',
      'Avan',
      'Cham',
    ],
  },
  african: {
    names: [
      'Mali',
      'Songhai',
      'Kanem Bornu',
      'Ethiopia',
      'Kilwa',
      'Mutapa',
      'Kongo',
      'Nubia',
      'Somalia',
      'Ajuraan',
      'Jolof',
      'Hausa',
      'Oyo',
      'Benin',
      'Ashanti',
      'Dahomey',
      'Zimbabwe',
      'Luba',
      'Madagascar',
      'Swahili',
    ],
    adjectives: [
      'Malian',
      'Songhai',
      'Kanem',
      'Ethiopian',
      'Kilwan',
      'Mutapan',
      'Kongolese',
      'Nubian',
      'Somali',
      'Ajuraani',
      'Jolof',
      'Hausa',
      'Oyo',
      'Edo',
      'Ashanti',
      'Dahomean',
      'Zimbabwean',
      'Luban',
      'Malagasy',
      'Swahili',
    ],
  },
  middle_eastern: {
    names: [
      'Persia',
      'Mamluks',
      'Arabia',
      'Yemen',
      'Oman',
      'Hejaz',
      'Iraq',
      'Syria',
      'Armenia',
      'Georgia',
      'Trebizond',
      'Candar',
      'Karaman',
      'Ramazan',
      'Dulkadir',
      'Ardabil',
      'Shirvan',
      'Mazandaran',
      'Fars',
      'Khorasan',
    ],
    adjectives: [
      'Persian',
      'Mamluk',
      'Arabian',
      'Yemeni',
      'Omani',
      'Hejazi',
      'Iraqi',
      'Syrian',
      'Armenian',
      'Georgian',
      'Trapezuntine',
      'Candarid',
      'Karamanid',
      'Ramazanid',
      'Dulkadirid',
      'Ardabili',
      'Shirvani',
      'Mazandarani',
      'Farsi',
      'Khorasani',
    ],
  },
  native: {
    names: [
      'Aztec Empire',
      'Inca Empire',
      'Maya',
      'Cherokee',
      'Iroquois',
      'Shawnee',
      'Creek',
      'Huron',
      'Sioux',
      'Apache',
      'Navajo',
      'Comanche',
      'Cahokia',
      'Pueblo',
      'Mapuche',
      'Tupinamba',
      'Guarani',
      'Arawak',
      'Carib',
      'Zapotec',
    ],
    adjectives: [
      'Aztec',
      'Incan',
      'Mayan',
      'Cherokee',
      'Iroquois',
      'Shawnee',
      'Creek',
      'Huron',
      'Sioux',
      'Apache',
      'Navajo',
      'Comanche',
      'Cahokian',
      'Puebloan',
      'Mapuche',
      'Tupinamba',
      'Guarani',
      'Arawak',
      'Carib',
      'Zapotec',
    ],
  },
}

// ─── Religions ───────────────────────────────────────────────────────────────

export const RELIGIONS = [
  { name: 'Catholic', group: 'christian' },
  { name: 'Orthodox', group: 'christian' },
  { name: 'Protestant', group: 'christian' },
  { name: 'Coptic', group: 'christian' },
  { name: 'Sunni', group: 'muslim' },
  { name: 'Shia', group: 'muslim' },
  { name: 'Ibadi', group: 'muslim' },
  { name: 'Hindu', group: 'dharmic' },
  { name: 'Buddhist', group: 'dharmic' },
  { name: 'Sikh', group: 'dharmic' },
  { name: 'Confucian', group: 'eastern' },
  { name: 'Shinto', group: 'eastern' },
  { name: 'Animist', group: 'pagan' },
  { name: 'Fetishist', group: 'pagan' },
  { name: 'Totemist', group: 'pagan' },
  { name: 'Tengri', group: 'pagan' },
  { name: 'Norse', group: 'pagan' },
  { name: 'Zoroastrian', group: 'zoroastrian' },
]

// ─── Tech groups ─────────────────────────────────────────────────────────────

export const TECH_GROUPS = [
  'western',
  'eastern',
  'ottoman',
  'muslim',
  'indian',
  'chinese',
  'nomad',
  'sub_saharan',
  'mesoamerican',
  'andean',
  'north_american',
]

// ─── Governments ─────────────────────────────────────────────────────────────

export const GOVERNMENTS = [
  'Feudal Monarchy',
  'Tribal Kingdom',
  'Merchant Republic',
  'Theocracy',
  'Steppe Nomads',
  'Despotic Monarchy',
  'Native Council',
  'Celestial Empire',
  'Elective Monarchy',
  'Oligarchic Republic',
  'Grand Duchy',
  'Holy Order',
  'Pirate Republic',
  'Free City',
  'Shogunate',
]

// ─── Utility ─────────────────────────────────────────────────────────────────

/**
 * Returns a random country name from the given culture group (or any group
 * if none specified). Uses the provided seed for deterministic selection.
 */
export function getRandomCountryName(
  seed: number,
  cultureGroup?: string,
): { name: string; adjective: string } {
  const rng = createRNG(seed)

  const groupKeys = Object.keys(CULTURE_GROUPS)
  const group =
    cultureGroup && CULTURE_GROUPS[cultureGroup]
      ? CULTURE_GROUPS[cultureGroup]
      : CULTURE_GROUPS[groupKeys[(rng() * groupKeys.length) | 0]]

  const idx = (rng() * group.names.length) | 0
  return {
    name: group.names[idx],
    adjective: group.adjectives[idx] ?? group.names[idx],
  }
}
